compiler:
  - gcc
cache: pip

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

matrix:
  include:
    - os: linux
      sudo: required
      language: generic
      deploy:
        skip_cleanup: true
        provider: releases
        api_key:
          secure: rR8zHcZNXb8Wi2v1APgJ9088+PPncVE1bQxZABzpmvjKpzR+xjdThj0JvQ6wOwHo32OaAMHXJ4djCIvcmnJ1VFjTfLT8KK0UFPG5QkzF6Edf3IiiDRj0My/CqvNqahvD3eIqxsWKr+jl5B3+w2tz/20CHiepdE1jKm+FKLu2qU/qjDnuMDWyz2dRBRGbBsMUOCbWh2AfB9PXpjpUrx2sKyfTVQZb9MC0bUo2yAjEfjRYJ/Sxg1x9uOQErcBa6ENYawVib+ZqicLHj2+KITHIm3jcdL3wov54+y9hk038GxSIk8XURhw3Z6M40kZqQ3C+5OwlgaklOow4WxkYm1j0hJfzrcWLXmxVdF7/BHsNwXepvS1MhxSNAPTlRzZVKFQVwucWCKJjZ2EDOSpi/sL1DM++16DoG58zEsI2KxeHSdzFe7CkmbNoHOzrLoYrnpHP5ksc0GmRWaLi+cZzcQEs4rlMPQJJWB4FUaWqQFmuWui6z564Q+xQGmXyExAdIjwhACK9yZb6wK8G7zCvYwwDSHz+nzcM+gbilU4HcbjVESJdF6VPuMJ48dcz6c6r+knKgdYS4EmtbabZ/rEC9hqVUXXgCRocEdt2+P/wXYQdoNf1GaaFjdKziRGz+p08TNtAEZ9MiGMJmHZ9nM+lrjpv8LAYavDmkTD0oMSdCwNWsms=
          file: dist/smc++-linux
          on:
            repo: terhorst/psmcpp
            tags: true
    - os: osx
      language: generic
      deploy:
        skip_cleanup: true
        provider: releases
        api_key:
          secure: rR8zHcZNXb8Wi2v1APgJ9088+PPncVE1bQxZABzpmvjKpzR+xjdThj0JvQ6wOwHo32OaAMHXJ4djCIvcmnJ1VFjTfLT8KK0UFPG5QkzF6Edf3IiiDRj0My/CqvNqahvD3eIqxsWKr+jl5B3+w2tz/20CHiepdE1jKm+FKLu2qU/qjDnuMDWyz2dRBRGbBsMUOCbWh2AfB9PXpjpUrx2sKyfTVQZb9MC0bUo2yAjEfjRYJ/Sxg1x9uOQErcBa6ENYawVib+ZqicLHj2+KITHIm3jcdL3wov54+y9hk038GxSIk8XURhw3Z6M40kZqQ3C+5OwlgaklOow4WxkYm1j0hJfzrcWLXmxVdF7/BHsNwXepvS1MhxSNAPTlRzZVKFQVwucWCKJjZ2EDOSpi/sL1DM++16DoG58zEsI2KxeHSdzFe7CkmbNoHOzrLoYrnpHP5ksc0GmRWaLi+cZzcQEs4rlMPQJJWB4FUaWqQFmuWui6z564Q+xQGmXyExAdIjwhACK9yZb6wK8G7zCvYwwDSHz+nzcM+gbilU4HcbjVESJdF6VPuMJ48dcz6c6r+knKgdYS4EmtbabZ/rEC9hqVUXXgCRocEdt2+P/wXYQdoNf1GaaFjdKziRGz+p08TNtAEZ9MiGMJmHZ9nM+lrjpv8LAYavDmkTD0oMSdCwNWsms=
        file: dist/smc++-osx
        on:
          repo: terhorst/psmcpp
          tags: true

script: ".travis/travis.sh"
