compiler:
    - gcc

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7
          env: TOXENV=py27
        - os: linux
          sudo: required
          python: 3.4
          env: TOXENV=py34
        - os: linux
          sudo: required
          python: 3.5
          env: TOXENV=py35
        - os: osx
          language: generic
          env: TOXENV=2.7
        - os: osx
          language: generic
          env: TOXENV=3.4
        - os: osx
          language: generic
          env: TOXENV=3.5

script: ".travis/travis.sh"
