compiler:
    - gcc

cache: pip

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

matrix:
    include:
        - os: linux
          sudo: required
          language: generic
        - os: osx
          language: generic

script: ".travis/travis.sh"
