os:
    - linux
    - osx

compiler:
    - gcc

script:
    - make 

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpfr gmp gsl; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get install -y libmpfr-dev libgmp-dev libgsl-dev; fi

deploy:
    provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file: "FILE TO UPLOAD"
    skip_cleanup: true
    on:
        tags: true
