os:
    - linux
    - osx

compiler:
    - gcc

language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpfr gmp gsl; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libmpfr-dev libgmp-dev libgsl0-dev; fi

install: "pip install -r requirements.txt"
