package:
  name: smcpp
  version: {{ GIT_DESCRIBE_TAG.lstrip("v") }}

source:
  git_url: ../

requirements:
  build:
    - python {{ python }}
    - nomkl
    - gcc >=4.8.5
    - libgcc 
    - openblas {{ openblas }}
    - git >=2.9.3
    - cython >=0.25
    - setuptools >=33.1
    - numpy >=1.10
    - gmp >=6.1.0
    - gsl >=2.2.1
    - mpc >=1.0.3
    - mpfr >=3.1.5
    - setuptools_scm >=1.15
  run:
    - python
    - nomkl
    - gcc >=4.8.5
    - libgcc
    - openblas
    - git >=2.9.3
    - cython >=0.25
    - setuptools >=33.1
    - numpy >=1.10
    - gnuplot >=4.6.0
    - gmp >=6.1.0
    - gsl >=2.2.1
    - mpc >=1.0.3
    - mpfr >=3.1.5
    - setuptools_scm >=1.15
    - pysam >=0.11
    - matplotlib >=2.0
    - pandas >=0.19
    - python-dateutil >=2.6
    - scipy >=0.18
    - six >=1.10
    - appdirs >=1.4
    - tqdm >=4.10
    - wrapt >=1.10
    - ad >=1.3.2
    - readline >=6.2
    - attrs >=17.2.0

about:
    home: https://github.com/popgenmethods/smcpp
    license: BSD
    license_file: LICENSE

test:
    imports:
        - smcpp
        - smcpp._smcpp
    source_files:
        - test/integration/test.sh
        - example/example.vcf.gz
        - example/example.vcf.gz.csi
    commands:
        - mkdir example
        - mv example.* example
        - ./test.sh smc++
