package:
  name: smcpp
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../

requirements:
  build:
    - python {{PY_VER}}*,>=3.5
    - gcc >=4.8
    - gsl 2.2.1
    - mpc 1.0.3
    - mpfr 3.1.5
    - cython >=0.25
    - numpy >=1.10
    - setuptools_scm >=1.15
    - git 2.9.3
  run:
    - conda
    - nomkl
    - numpy >=1.10
    - python {{PY_VER}}*,>=3.5
    - libgcc >=4.8
    - gnuplot 4.6.0
    - gmp 6.1.0
    - gsl 2.2.1
    - mpc 1.0.3
    - mpfr 3.1.5
    - setuptools_scm >=1.15
    - pysam >=0.10
    - matplotlib >=2.0
    - pandas >=0.19
    - python-dateutil >=2.6
    - scipy >=0.18
    - six >=1.10
    - appdirs >=1.4
    - tqdm >=4.10
    - seaborn >=0.7
    - wrapt >=1.10
    - ad >=1.3.2
    - readline 6.2

about:
  home: https://github.com/popgenmethods/smcpp
  license: BSD
  license_file: LICENSE

test:
  imports:
    - smcpp
    - smcpp._smcpp
